In [17]:
import pandas as pd

In [19]:

# df=pd.read_csv('C:/Users/M/Desktop/정제/202304.csv')
code=pd.read_excel('C:/Users/M/Desktop/파일정리/데이터/행정코드/전국 행정동 코드정보.xlsx')
code

       SIDO_NM SGG_NM ADMI_NM   ADMI_CD          FULL_NM  BASE_YM
0        서울특별시    종로구   청운효자동  11110515  서울특별시 종로구 청운효자동   202301
1        서울특별시    종로구     사직동  11110530    서울특별시 종로구 사직동   202301
2        서울특별시    종로구     삼청동  11110540    서울특별시 종로구 삼청동   202301
3        서울특별시    종로구     부암동  11110550    서울특별시 종로구 부암동   202301
4        서울특별시    종로구     평창동  11110560    서울특별시 종로구 평창동   202301
...        ...    ...     ...       ...              ...      ...
52600  전북특별자치도    부안군     백산면  52800380  전북특별자치도 부안군 백산면   202403
52601  전북특별자치도    부안군     상서면  52800390  전북특별자치도 부안군 상서면   202403
52602  전북특별자치도    부안군     하서면  52800400  전북특별자치도 부안군 하서면   202403
52603  전북특별자치도    부안군     줄포면  52800410  전북특별자치도 부안군 줄포면   202403
52604  전북특별자치도    부안군     위도면  52800420  전북특별자치도 부안군 위도면   202403

[52605 rows x 6 columns]

In [20]:
code=code.rename(columns={'ADMI_CD':'code'})        ## 위치데이터 컬럼명을 code로 통일
code=code.drop_duplicates(subset=['code'])
code=code[code.code<20000000]                       #  20000000미만 값이 서울데이터
code
# df_merge=pd.merge(code,df)
# df_merge.to_csv('202304merge.csv')

#code.to_csv('행정코드정제.csv')                   # 저장

     SIDO_NM SGG_NM ADMI_NM      code          FULL_NM  BASE_YM
0      서울특별시    종로구   청운효자동  11110515  서울특별시 종로구 청운효자동   202301
1      서울특별시    종로구     사직동  11110530    서울특별시 종로구 사직동   202301
2      서울특별시    종로구     삼청동  11110540    서울특별시 종로구 삼청동   202301
3      서울특별시    종로구     부암동  11110550    서울특별시 종로구 부암동   202301
4      서울특별시    종로구     평창동  11110560    서울특별시 종로구 평창동   202301
...      ...    ...     ...       ...              ...      ...
422    서울특별시    강동구    성내3동  11740660   서울특별시 강동구 성내3동   202301
423    서울특별시    강동구      길동  11740685     서울특별시 강동구 길동   202301
424    서울특별시    강동구    둔촌1동  11740690   서울특별시 강동구 둔촌1동   202301
425    서울특별시    강동구    둔촌2동  11740700   서울특별시 강동구 둔촌2동   202301
7372   서울특별시    강남구    개포3동  11680675   서울특별시 강남구 개포3동   202303

[427 rows x 6 columns]